#!/usr/bin/env python3
"""agy_transcript.py — LEVEL 3 output transport for run_gemini.sh.

Reads one agy invocation's answer back out of agy's own on-disk transcript. This is a
COMPATIBILITY FALLBACK only, used when agy exits 0 but prints nothing (the historical
agy bug #76 behavior on Windows). agy 1.1.8 prints cleanly on both `--output-format json`
and `--output-format text`, so this path should not normally fire.

It does NOT launch agy. run_gemini.sh has already run it, in a fresh per-invocation
workspace directory; this script only recovers what that run wrote. (The previous
`agy_capture.py` launched a SECOND agy process to capture an answer, which both cost an
extra model call and made it impossible to tie the recovered text to the original run.)

Correlation to the current invocation — all of these must hold, so a previous run's
transcript can never be accepted as this run's answer:
  1. The conversation is identified either by the id agy printed on stdout for THIS run
     (--conversation-id) or by looking up agy's own cache keyed on the unique, freshly
     created workspace directory this run used (--workspace).
  2. The transcript file's mtime must be at/after this invocation's start (--since).

Usage:
  agy_transcript.py --workspace <dir> --since <epoch_seconds> [--conversation-id <id>]

Prints the recovered answer on stdout. Exit 0 = recovered; non-zero = nothing usable
(the caller then fails the panelist rather than returning empty text).
"""
import argparse
import json
import os
import sys
from pathlib import Path

# agy answers routinely contain non-Latin-1 glyphs. On Windows, Python defaults stdout to
# cp1252 when redirected to a pipe/file, which raises UnicodeEncodeError mid-write and
# leaves the output empty. Force UTF-8.
try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

HOME = Path(os.path.expanduser("~"))
CLI = Path(os.environ.get("AGY_CLI_DIR", str(HOME / ".gemini" / "antigravity-cli")))
LAST_CONVERSATIONS = CLI / "cache" / "last_conversations.json"
BRAIN = CLI / "brain"

# A MODEL turn carrying final answer text.
MODEL_TYPES = {"PLANNER_RESPONSE", "ASSISTANT_RESPONSE", "MODEL_RESPONSE", "RESPONSE"}

# Filesystem mtime granularity / clock skew slack, in seconds.
MTIME_SLACK = 5.0


def _norm(p: str) -> str:
    """Normalize a path for comparison across MSYS ('/c/...') and native ('C:\\...') spellings."""
    return p.replace("\\", "/").rstrip("/").lower()


def conv_id_for_workspace(ws: str):
    """Look up the conversation agy opened for this workspace, from agy's own cache."""
    try:
        mapping = json.loads(LAST_CONVERSATIONS.read_text(encoding="utf-8"))
    except Exception:
        return None
    if not isinstance(mapping, dict):
        return None

    target = _norm(ws)
    for key, val in mapping.items():
        if _norm(key) == target:
            return val

    # Path spellings differ across MSYS/native/8.3-shortened forms. The workspace basename is
    # generated by mktemp and is unique on this machine, so an unambiguous basename match is a
    # safe second pass. Ambiguity is treated as no match rather than guessing.
    base = os.path.basename(target)
    if base:
        matches = {v for k, v in mapping.items() if os.path.basename(_norm(k)) == base}
        if len(matches) == 1:
            return matches.pop()
    return None


def transcript_for(conv_id: str) -> Path:
    return BRAIN / conv_id / ".system_generated" / "logs" / "transcript.jsonl"


def model_text(tpath: Path) -> str:
    """Concatenate this conversation's MODEL answer turns, in transcript order."""
    parts = []
    for line in tpath.read_text(encoding="utf-8", errors="replace").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            rec = json.loads(line)
        except Exception:
            continue
        if not isinstance(rec, dict):
            continue
        if rec.get("source") != "MODEL" or rec.get("type") not in MODEL_TYPES:
            continue
        if rec.get("status") not in (None, "DONE"):
            continue
        content = rec.get("content")
        if isinstance(content, str) and content.strip():
            parts.append(content)
    return "\n".join(parts).strip()


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--workspace", required=True,
                    help="the fresh workspace dir this agy invocation ran in")
    ap.add_argument("--since", required=True, type=float,
                    help="epoch seconds when this invocation started; older transcripts are rejected")
    ap.add_argument("--conversation-id", default="",
                    help="conversation id agy printed for this run, when known")
    args = ap.parse_args()

    conv_id = args.conversation_id.strip() or conv_id_for_workspace(args.workspace)
    if not conv_id:
        sys.stderr.write(
            "agy_transcript: no conversation could be tied to this invocation "
            f"(workspace={args.workspace})\n")
        return 1

    tpath = transcript_for(conv_id)
    if not tpath.exists():
        sys.stderr.write(f"agy_transcript: no transcript for conversation {conv_id}\n")
        return 1

    # Staleness gate: refuse a transcript that predates this invocation.
    try:
        mtime = tpath.stat().st_mtime
    except OSError as exc:
        sys.stderr.write(f"agy_transcript: cannot stat transcript {tpath}: {exc}\n")
        return 1
    if mtime < args.since - MTIME_SLACK:
        sys.stderr.write(
            f"agy_transcript: REJECTED stale transcript for conversation {conv_id} "
            f"(mtime {mtime:.0f} < invocation start {args.since:.0f}); refusing to pass a "
            "previous run's answer off as this one's\n")
        return 1

    text = model_text(tpath)
    if not text:
        sys.stderr.write(
            f"agy_transcript: transcript for conversation {conv_id} holds no MODEL answer\n")
        return 1

    sys.stdout.write(text + "\n")
    sys.stderr.write(f"agy_transcript: recovered conversation {conv_id}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
